### ISSUE TITLE
new commands

### ISSUE THREAD

**Issue by Celllnside** [lorencerri/discord-bot-template#22]
i tried making a new command but after i made it the bot says nothing back the pre made commands work though
here is the code for the command

const { Command } = require('discord-akairo');

class VampCommand extends Command {
    constructor() {
        super('who is vamp', {
            aliases: ['who is vamp']
        });
    }

    async exec(message) {
        return message.channel.send('a woman')
    }
}

module.exports = VampCommand;

it does nothing 
![image](https://user-images.githubusercontent.com/71746732/112087597-4244f680-8b5c-11eb-8382-142837453e5d.png)

**Comment by loom4k** [comment]
Hello, this answer might be a bit late but I would never recommend having a command name with spaces. This can create a lot of confusion with the arguments. Try replacing the spaces with `-` instead maybe?

**Comment by lorencerri** [comment]
The template now uses [`@sapphiredev/framework`](https://github.com/sapphiredev/framework)
